from .api import SUMMER_SMILES_API_BASE_URL, ENDPOINTS
from .paths import (
    FRENCH_PAGES_PATH,
    ENGLISH_PAGES_PATH,
    FRENCH_POSTS_PATH,
    ENGLISH_POSTS_PATH,
    FRENCH_PRODUCTS_PATH,
    ENGLISH_PRODUCTS_PATH,
    VECTOR_STORE_ID_PATH,
)
from .ai import OPENAI_MODEL

__all__ = [
    "SUMMER_SMILES_API_BASE_URL",
    "ENDPOINTS",
    "FRENCH_PAGES_PATH",
    "ENGLISH_PAGES_PATH",
    "FRENCH_POSTS_PATH",
    "ENGLISH_POSTS_PATH",
    "FRENCH_PRODUCTS_PATH",
    "ENGLISH_PRODUCTS_PATH",
    "VECTOR_STORE_ID_PATH",
    "OPENAI_MODEL",
]
